<a href="https://colab.research.google.com/github/apxunov/intelligent-data-analysis/blob/main/hometask2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Во всех задачах необходимо написать код решения внутри функции и убедиться, что она работает, с помощью `assert` на выражение с использованием этой функции для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

In [2]:
import numpy as np

# **Задание 1.**
Напишем функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам.
<br> 
В нашем случае вес экзамена равен 0.3, вес домашек - 0.4, вес контрольной - 0.2, вес самостоятельных - 0.1. 
<br>
Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

$Mark = 0.3*Ex + 0.4*Hw + 0.2*Cw + 0.1*Test$ 

In [21]:
def result_mark(weights: np.array, marks: np.array) -> int:
  return np.dot(weights, marks, out=None).round()

In [22]:
result_mark([0.3, 0.4, 0.2, 0.1], [7, 10, 8, 6])

8.0

In [23]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([7, 10, 8, 6])

assert result_mark(weights, marks) == 8

In [24]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([7, 0, 8, 6])

assert result_mark(weights, marks) == 4

# **Задание 2.**
Напишем функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. 
<br>
Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [25]:
def change_array(array: np.array, number: int) -> np.array:
    array[0::3] = number
    return array

In [26]:
change_array(np.array([3, 5, 1, 0, -3, 22, 213436]), -111)

array([-111,    5,    1, -111,   -3,   22, -111])

In [27]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111

assert np.allclose(change_array(array, number), np.array([-111, 5, 1, -111, -3, 22, -111]))

In [28]:
array = np.array([3, 14, 15, 92, 6])
number = 8

assert np.allclose(change_array(array, number), np.array([8, 14, 15, 8, 6]))

# **Задание 3.**
Напишем функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. 
<br>
Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])`
<br> 
**важно:** не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть .`ndim` от него равно 1).

In [29]:
def find_close(array1: np.array, array2: np.array, precision: float) -> np.array:
  newArr = np.abs(array1 - array2)
  return np.array(np.where(newArr < precision)).flatten()

find_close(np.array([1.5, 0.5, 2, -4.1, -3, 6, -1]), np.array([1.2, 0.5, 1, -4.0,  3, 0, -1.2]), 0.5)

array([0, 1, 3, 6])

In [30]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4.0,  3, 0, -1.2])
precision = 0.5
res = find_close(array1, array2, precision)

assert res.ndim == 1
assert np.allclose(res, np.array([0, 1, 3, 6]))

In [31]:
array1 = np.array([3.1415, 2.7182, 1.6180, 6.6261])
array2 = np.array([6.6730, 1.3807, -1,     6.0222])
precision = 1.7
res = find_close(array1, array2, precision)

assert res.ndim == 1
assert np.allclose(res, np.array([1, 3]))

# **Задание 4.**

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. 
<br>
Например, если на вход поступает матрица:
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5
\end{pmatrix}
<br>
, то ответом будет: 
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5
\end{pmatrix}

In [32]:
def block_matrix(block: np.array) -> np.array:
  return np.tile(block, (2, 2))

In [33]:
block = np.array([[1, 3, 3], [7, 0, 0]])

assert np.allclose(
    block_matrix(block),
    np.array([[1, 3, 3, 1, 3, 3],
              [7, 0, 0, 7, 0, 0],
              [1, 3, 3, 1, 3, 3],
              [7, 0, 0, 7, 0, 0]])
)

# **Задание 5.**
Напишем функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. 
Например, если на вход поступает матрица:
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix}
, то ответом будет 32.
<br>Элементы матрицы будем считать целочисленными.

1. Найдем диагональные элементы – `np.diag()`
2. Найдем ненулевые среди диагональных элементов – `np.nonzero()` выдаст нам их индексы
3. Перемножим элементы полученного массива с помощью `np.prod()`

In [34]:
def diag_prod(matrix: np.array) -> int:
    diag = np.diag(matrix)
    return np.prod(diag[np.nonzero(diag)])

In [35]:
mtx = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

diag_prod(matrix=mtx)

32

In [36]:
matrix = np.array([[0, 1, 2, 3],
                   [4, 5, 6, 7],
                   [8, 9, 10, 11],
                   [12, 13, 14, 15]])

assert diag_prod(matrix) == 750

# **Задание 6.** 

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать нормализацию данных, чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица:
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
то результатом с точностью до сотых будет матрица:
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}

Учтите, что в вашем матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему.

Подсказка. Казалось бы, при чем тут деление на ноль.

In [37]:
def normalize(matrix: np.array) -> np.array:
    means = np.mean(matrix, axis=0)
    stds = np.std(matrix, axis=0)
    stds[np.where(stds == 0)] = 1
    mtx = (matrix - means) / stds
    return mtx

In [38]:
matrix = np.array([[4, 4, 4200], 
                   [4, 10, 5000], 
                   [4, 2, 1000]])
normalize(matrix)

array([[ 0.        , -0.39223227,  0.46291005],
       [ 0.        ,  1.37281295,  0.9258201 ],
       [ 0.        , -0.98058068, -1.38873015]])

In [39]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])

assert np.allclose(
    normalize(matrix),
    np.array([[ 0.7071, -0.39223,  0.46291],
              [-1.4142,  1.37281,  0.92582],
              [ 0.7071, -0.98058, -1.38873]])
)

In [40]:
matrix = np.array([[-7, 2, 42], [2, 10, 50], [5, 4, 10]])

assert np.allclose(
    normalize(matrix),
    np.array([[-1.37281, -0.98058,  0.46291],
              [ 0.39223,  1.37281,  0.92582],
              [ 0.98058, -0.39223, -1.38873]])
)

# **Задание 7.**
Напишем функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмём $0$). 
<br>
Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.


In [41]:
def antiderivative(coefs: np.array) -> np.array:
    return np.polyint(coefs, m=1, k=0)

antiderivative(np.array([4, 6, 0, 1]))

array([1., 2., 0., 1., 0.])

In [42]:
coefs = np.array([4, 6, 0, 1])

assert np.allclose(
    antiderivative(coefs),
    np.array([1., 2., 0., 1., 0.])
)

In [44]:
coefs = np.array([1, 7, -12, 21, -6])

assert np.allclose(
    antiderivative(coefs),
    np.array([ 0.2, 1.75, -4., 10.5, -6., 0.])
)

# **Задание 8.**

Напишем функцию, делающую данную треугольную матрицу симметричной. 
<br>
Например, если на вход поступает матрица:$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$то на выходе должна быть матрица:$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

1. Поменяем строки и столбцы исходной матрицы местами `mtx = np.moveaxis(matrix, 0, -1)`.
2. Сложим исходную материцу с матрицей из пункта 1. Нули в этих матрицах расположены по разные стороны от главной диагонали. Следовательно, сложение даст нам некоторую зеркальную версию исходной матрицы относительно главное диагонали – за одним исключением: главные диагонали матриц сложатся. 
3. Чтобы избежать результата сложения матриц, заполним главную диагональ результирующей матрицы значениями из главной диагонали исходной матрицы с помощью `np.fill_diagonal`

In [45]:
def make_symmetric(matrix: np.array) -> np.array:
  mtx = np.moveaxis(matrix, 0, -1)
  res = mtx + matrix 
  np.fill_diagonal(res, np.diagonal(matrix))
  return res

In [46]:
make_symmetric(np.array([
                         [1, 2, 3, 4], 
                         [0, 5, 6, 7], 
                         [0, 0, 8, 9], 
                         [0, 0, 0, 10]
                         ]))

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

In [47]:
matrix = np.array([[10, 21, 32, 49], [0, 53, 62, 78], [0, 0, 82, 92], [0, 0, 0, 10]])

assert np.allclose(
    make_symmetric(matrix),
    np.array([[10, 21, 32, 49],
              [21, 53, 62, 78],
              [32, 62, 82, 92],
              [49, 78, 92, 10]])
)

In [48]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])

assert np.allclose(
    make_symmetric(matrix),
    np.array([[ 1,  2,  3,  4],
              [ 2,  5,  6,  7],
              [ 3,  6,  8,  9],
              [ 4,  7,  9, 10]])
)

# **Задание 9.**
Напишем функцию, создающую прямоугольную матрицу из $m$ одинаковых строк, заполненных последовательными натуральными числами от $a$ до $b$ включительно в возрастающем порядке. 
<br>Например, если $m = 5$, $a = 3$, $b = 10$, то на выходе будет матрица:
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

1. С помощью `np.arrange(a, b+1)` создадим `np.array` $[a, b]$.
2. Повторим получившийся массив $m$ раз
3. Поменяем размерность с помощью `np.reshape`
4. Транспонируем получившуюся матрицу с помощью `np.T`

In [49]:
def construct_matrix(m: int, a: int, b: int) -> np.array:
  arr = np.arange(a, b+1)
  arr = arr.repeat(m).reshape(len(arr), m).T
  return arr

In [50]:
construct_matrix(5, 3, 10)

array([[ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [51]:
m = 5
a = 3
b = 10

assert np.allclose(
    construct_matrix(m, a, b),
    np.array([[ 3,  4,  5,  6,  7,  8,  9, 10],
              [ 3,  4,  5,  6,  7,  8,  9, 10],
              [ 3,  4,  5,  6,  7,  8,  9, 10],
              [ 3,  4,  5,  6,  7,  8,  9, 10],
              [ 3,  4,  5,  6,  7,  8,  9, 10]])
)

In [52]:
m = 3
a = 2
b = 6

assert np.allclose(
    construct_matrix(m, a, b),
    np.array([[2, 3, 4, 5, 6],
              [2, 3, 4, 5, 6],
              [2, 3, 4, 5, 6]])
)

# **Задание 10.**
Напишем функцию, вычисляющую косинусную близость двух векторов. 
<br>Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет $-0.25$.

Для двух векторов атрибутов, $A$ и $B$ , косинусное сходство, $cos (θ)$, представляется согласно следующей формуле:
$$ similarity = cos(θ) = \frac{A \cdot B}{||A|| \ ||B||} = \frac{\sum_{i=1}^n  A_i \cdot B_i}{\sqrt{\sum_{i=1}^n  A_i^2} \cdot \sqrt{\sum_{i=1}^n  B_i^2}}$$


In [53]:
def cosine_similarity(vec1: np.array, vec2: np.array) -> float:
  sqrtVec1pow, sqrtVec2pow = np.sqrt(np.sum(vec1 ** 2)), np.sqrt(np.sum(vec2 ** 2))
  numerator = np.dot(vec1, vec2)
  denominator = sqrtVec1pow * sqrtVec2pow
  res = numerator / denominator
  return res

In [54]:
vec1 = np.array([-2, 1,  0, -5, 4, 3, -3])
vec2 = np.array([ 0, 2, -2, 10, 6, 0,  0])
cosine_similarity(vec1, vec2)

-0.25

In [55]:
vec1 = np.array([-2, 1,  0, -5, 4, 3, -3])
vec2 = np.array([ 0, 2, -2, 10, 6, 0,  0])

assert np.allclose(cosine_similarity(vec1, vec2), -0.25)

In [56]:
vec1 = np.array([-4, 2,  9, -8, 9, 0, -2])
vec2 = np.array([ 3, 2, -4, -1, 3, 2,  2])

assert np.allclose(cosine_similarity(vec1, vec2), -0.119929)